-08-20 20:53:49,646: ERROR/MainProcess] Task tasks.pdf_processor[f988af99-4af2-4997-86b4-728e51df9644] raised unexpected: ProgrammingError(1064, "1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'C061514C_40.pdf''' at line 1", '42000')
Traceback (most recent call last):
  File "c:\projects\scrapper\scrapper-env\lib\site-packages\celery\app\trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\projects\scrapper\scrapper-env\lib\site-packages\celery\app\trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\Projects\scrapper\tasks.py", line 183, in pdf_processor
    cursor.execute(sql,data)
  File "c:\projects\scrapper\scrapper-env\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "c:\projects\scrapper\scrapper-env\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "c:\projects\scrapper\scrapper-env\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'C061514C_40.pdf''' at line 1